### ISSUE TITLE
服务器核心 / 内存数量太多时显示不全

### ISSUE THREAD

**Issue by sanaprix** [hi2shark/nazhua#1]
~~如图。该服务器是一个 28Core 32G RAM 60G SSD 的服务器。字数太多，前面 28C 的 28 被省略了。~~

![image](https://github.com/user-attachments/assets/7c0c9b21-5873-4ab1-95c9-63082df3dda2)

~~小鸡没有这个问题。似乎只能最多显示 7 个字符。~~
![image](https://github.com/user-attachments/assets/2573eed9-1568-4035-9c9e-a0acb1fe2343)

**Comment by hi2shark** [comment]
啊这，，，贫穷限制了我的想象

我需要看看大佬的探针，查看CPU那串字符串的具体内容，应该是正则匹配没匹配到核心数量
