### ISSUE TITLE
会不会增加登陆选项

### ISSUE THREAD

**Issue by whatmeans** [hi2shark/nazhua#10]
我的nezha大部分服务器是对游客隐藏的。用nazhua不登陆好像不能显示

**Comment by hi2shark** [comment]
哪吒v1是可以的；
哪吒v0需要看看是否能正常继承cookie

**Comment by whatmeans** [comment]
> 哪吒v1是可以的； 哪吒v0需要看看是否能正常继承cookie

用的是v0，试了下应该没继承。本机nezha登陆后，nazhua进去还是空的。。。

**Comment by hi2shark** [comment]
> > 哪吒v1是可以的； 哪吒v0需要看看是否能正常继承cookie
> 
> 用的是v0，试了下应该没继承。本机nezha登陆后，nazhua进去还是空的。。。

我大概看了一下，因为哪吒v0前后台模板很多路由的设置都是‘/xxx'，在不修改哪吒v0模板的情况下，尝试让哪吒成为二级目录的方案行不通；
只能尝试让nazhua成为二级目录，但需要单独打包配置/{base}/，这个就需要你下载项目后自己执行，，，，可能对你来说，有点麻烦。
😅😅😅

**Comment by hi2shark** [comment]
https://github.com/hi2shark/nazhua/releases/tag/v0.4.12
下载构建物：`v0-nazhua.zip`，然后用nginx或者caddy之类的web服务器，降你的探针面板子目录`/nazhua/`指向这个目录
参考的nginx配置示例，具体需要自行调试，如遇问题，建议咨询GPT解答；
```nginx
server {
 # ...哪吒的其它配置

 # 把/nazhua指向目录/home/wwwroot/html
 location /nazhua {
    alias /home/wwwroot/html;
    try_files $uri $uri/ /index.html;
  }
}
```

**Comment by whatmeans** [comment]
> https://github.com/hi2shark/nazhua/releases/tag/v0.4.12 下载构建物：`v0-nazhua.zip`，然后用nginx或者caddy之类的web服务器，将你的探针面板网站的子目录`/nazhua/`指向这个目录 参考的nginx配置示例，具体需要自行调试，如遇问题，建议咨询GPT解答；
> 
> ```nginx
> server {
>  # ...哪吒的其它配置
> 
>  # 把/nazhua指向目录/home/wwwroot/html
>  location /nazhua {
>     alias /home/wwwroot/html;
>     try_files $uri $uri/ /index.html;
>   }
> }
> ```

子目录方法成功，感谢更新！

**Comment by hi2shark** [comment]
> > https://github.com/hi2shark/nazhua/releases/tag/v0.4.12 下载构建物：`v0-nazhua.zip`，然后用nginx或者caddy之类的web服务器，将你的探针面板网站的子目录`/nazhua/`指向这个目录 参考的nginx配置示例，具体需要自行调试，如遇问题，建议咨询GPT解答；
> > ```nginx
> > server {
> >  # ...哪吒的其它配置
> > 
> >  # 把/nazhua指向目录/home/wwwroot/html
> >  location /nazhua {
> >     alias /home/wwwroot/html;
> >     try_files $uri $uri/ /index.html;
> >   }
> > }
> > ```
> 
> 子目录方法成功，感谢更新！

这个方式不方便构建docker镜像（因为有点重复套nginx之类的），后续需要下载压缩包手动更新
