### ISSUE TITLE
小小bug

### ISSUE THREAD

**Issue by whatmeans** [hi2shark/nazhua#11]
是这样的，nezha公开备注这里默认没有多年付的参数，然后官方issues里有个操作是把多年付的信息写在amount参数里面，把cycle参数清空。如下图。
![nezha_issues](https://github.com/user-attachments/assets/609e92d8-126e-4852-85b2-aedcc82bd7ae)

但是这样后，nazhua里价格显示那边会显示多个 “/ ” ,如下图。能否判断下cycle参数是否存在，然后再决定加不加“/”
![nazhua](https://github.com/user-attachments/assets/2979b798-072f-4f5a-aa24-3ead69499f9e)

**Comment by hi2shark** [comment]
之前没处理好这块，，，已处理

**Comment by hi2shark** [comment]
https://github.com/hi2shark/nazhua/releases/tag/v0.4.15
