### ISSUE TITLE
同一台服务器添加到多个分组时，排序靠后的分组无法显示服务器

### ISSUE THREAD

**Issue by sakelaer** [hi2shark/nazhua#5]
当前使用版本：v0.4.3
哪吒后端版本：v1.1.2

**现象：当服务器划分到多个分组的时候，排序更靠后的分组无法显示这些服务器**

**问题：**
**1. 为DMIT US的服务器创建了US的分组，也同时创建了DMIT的分组**
<img width="524" alt="Screenshot 2024-12-07 at 14 13 28" src="https://github.com/user-attachments/assets/2b7c3fcf-6631-4e5d-97c2-565a2381c48e">
<img width="526" alt="Screenshot 2024-12-07 at 14 13 37" src="https://github.com/user-attachments/assets/f8aebff7-55d6-433e-adc4-2701c6967ad6">

**2.当前US的分组更靠前，选择US分组时，服务器信息能够正常显示**
<img width="875" alt="Screenshot 2024-12-07 at 14 12 52" src="https://github.com/user-attachments/assets/3c6f756b-3b59-411b-b1ed-ae57040017e2">

**3. 当选择更靠后的DMIT分组时，无法显示这些添加了多个分组的服务器**
<img width="579" alt="Screenshot 2024-12-07 at 14 12 58" src="https://github.com/user-attachments/assets/694d445e-d04e-4cf4-b677-8cde9c5ef0a3">

**4. 分组排在最后的CN，因为内部服务器没有重复添加，因此可以正常显示**
<img width="848" alt="Screenshot 2024-12-07 at 14 21 24" src="https://github.com/user-attachments/assets/bafae661-f607-4fc6-bf7a-37ca50a24aba">

**5. 手动创建一个新的腾讯云分组并添加这几台CN的服务器后，腾讯云分组无法显示这些服务器**
<img width="574" alt="Screenshot 2024-12-07 at 14 23 11" src="https://github.com/user-attachments/assets/f8fa8b2b-c617-48fb-8c05-2ffa10b50fb7">
<img width="349" alt="Screenshot 2024-12-07 at 14 23 17" src="https://github.com/user-attachments/assets/f3a6efda-5698-46bf-b57f-11014d82d62d">

**6. 在更靠前的分组里添加腾讯云这些服务器，CN分组里的服务器便不再显示**
<img width="1332" alt="Screenshot 2024-12-07 at 14 31 12" src="https://github.com/user-attachments/assets/bfcd2dad-0654-4ecd-ba1f-69f4c0077b73">
<img width="992" alt="Screenshot 2024-12-07 at 14 31 16" src="https://github.com/user-attachments/assets/0e3d830d-b222-4f18-849e-291fec998f90">

**Comment by hi2shark** [comment]
此处兼容的是v0单一tag模式，v1没有兼容，等待后续修正

**Comment by hi2shark** [comment]
已修复，等待v0.4.5版本更新
