### ISSUE TITLE
配置生成器导出的哪吒V1控制台自定义代码不生效

### ISSUE THREAD

**Issue by luoli233** [hi2shark/nazhua#6]
哪吒版本“1.1.2”，在后台自定义代码使用后完全没有效果，前台F12看了一下是有代码的，但是没生效
导出的配置为
`<script>
  window.$$nazhuaConfig = {
  buyBtnText: '官网',
  customCodeMap: {
    MNS: {
      name: '马纳萨斯',
      country: '美国',
      x: 261,
      y: 186,
    },
  },
};
</script>`

**Comment by hi2shark** [comment]
昨晚上更新官方兼容v1的0.4.3精力耗损过渡，没有仔细验证这个配置方案 ———— 就是写成BUG了
你在配置项里面生成新的，并在nazhua的0.4.4版后使用

**Comment by luoli233** [comment]
> 昨晚上更新官方兼容v1的0.4.3精力耗损过渡，没有仔细验证这个配置方案 ———— 就是写成BUG了 你在配置项里面生成新的，并在nazhua的0.4.4版后使用

看了一下官方后台的版本还是0.4.3，官方的什么时候能更新0.4.4呢

**Comment by hi2shark** [comment]
> > 昨晚上更新官方兼容v1的0.4.3精力耗损过渡，没有仔细验证这个配置方案 ———— 就是写成BUG了 你在配置项里面生成新的，并在nazhua的0.4.4版后使用
> 
> 看了一下官方后台的版本还是0.4.3，官方的什么时候能更新0.4.4呢

这个目前要等官方库更新，我在提建议了（希望以后能手动填写或者选择版本号吧

**Comment by hi2shark** [comment]
官方已更新
https://github.com/nezhahq/nezha/releases/tag/v1.1.3
