### ISSUE TITLE
小鸡如果是大陆的，地图上不显示。

### ISSUE THREAD

**Issue by U201413497** [hi2shark/nazhua#8]
小鸡如果是大陆的，地图上不显示。

**Comment by hi2shark** [comment]
参阅Readme中的内容：
## 关于点阵地图  
点阵地图是一个失真的地图，地图边际与城市位置都不是真实的经纬度坐标，因此无法通过经纬度来定位城市。  
需要在是[Nazhua配置生成器](https://hi2shark.github.io/nazhua-generator/)中，拾取点阵地图上的坐标，然后在`config.js`中配置`customCodeMap`来自定义地图点信息。  
如何指定节点的地理位置？  
在哪吒监控后台，给节点的公开备注对象中，添加一个`customData`对象，并指定`location`的代码；  
关于都有哪些内置的地理位置代码，需要在[Nazhua配置生成器](https://hi2shark.github.io/nazhua-generator/)中查看。  
示例
```json
{
  "customData": {
    "location": "HKG"
  }
}
```
对于几个我常见的国别位置，添加了默认映射位置，会自动显示在地图上。  
Tips: 中国大陆地区默认在首都：北京（tips，这一个在0.4.6后生效）  
Tips: 美国默认在最常买的位置：洛杉矶    

需要你自己指定位置，如果指定的位置没有内置，需要自己设定，可以用配置生成器处理
