### ISSUE TITLE
后添加的网络监控，在面板上显示时间不同步

### ISSUE THREAD

**Issue by fxxzz** [hi2shark/nazhua#9]
nezha 1.1.2
nezhua 0.4.3

后期添加的网络监控，出现在最早的时间点
<img width="943" alt="Screenshot 2024-12-09 at 03 06 20" src="https://github.com/user-attachments/assets/277413d8-ca8d-435a-b9a3-260aedadc3de">

<img width="1119" alt="Screenshot 2024-12-09 at 03 06 00" src="https://github.com/user-attachments/assets/1a55107a-3dcf-4ac6-9964-22c1013dd87e">

**Comment by hi2shark** [comment]
已修复这个问题，需要更新至0.4.7
https://github.com/hi2shark/nazhua/releases
https://github.com/hi2shark/nazhua/pkgs/container/nazhua
